source 'https://rubygems.org'

gem 'rails', '3.2.14'

gem 'pg'

gem 'jquery-rails'

gem 'haml-rails'

# will need this gem to convert erb files generated by Devise
gem 'erb2haml' # then run: rake haml:replace_erbs

gem 'devise'
gem 'devise_invitable', '~> 1.1.0'

# gem 'cancan'

gem 'chartkick'

gem 'carrierwave'
gem 'fog', '~> 1.3.1'

gem 'will_paginate', '~> 3.0'

gem 'best_in_place'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :production, :test do
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'better_errors'
  gem 'binding_of_caller'

  gem 'rspec-rails'
  gem 'database_cleaner'
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'faker'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
